### ISSUE TITLE
Convert sample app to Kotlin

### ISSUE THREAD

**Issue by andyb129** [andyb129/BeerProgressView#10]
Convert the sample app classes to Kotlin (I'll then merge these to the 'kotlin-version' branch so create feature branch from that). 

- MainActivity
- PourBeerTask

**Comment by mezpahlan** [comment]
Taking this one one.

**Comment by mezpahlan** [comment]
Good evening Mr. B. 

I am having some difficulty converting the sample app in particular the `MainActivity`. On the face of it the initial conversion is straight forward however as I mentioned in Slack the `AsyncTask` is proving a bit thorny. Here's what I have:

* I can't restart the `AsyncTask`. Maybe I'm being dense but it seems that once the task completes that's it. It's been ages since I've used one so happy hear otherwise.
* In the Java `MainActivity` the `AsyncTask` gets effectively *reset* such that it can be restarted by `null`ing the reference and reassigning which works pretty well in Java.
* In Kotlin, however I cannot `null` a `val` reference. So I make it a `var` so that I can set it to `null` and reinitialise it when I switch tabs. However I cannot do that either as I need to change the type from a `PourBeerTask` to a `PourBeerTask?` - a nullable type.
* I end up writing Kotlin code but it is still littered with `null` checks.

In doing this I fear that I'm not writing idiomatic Kotlin code and carrying over bad practices from Java? Thoughts?

**Comment by mezpahlan** [comment]
I've added a PR (#13) to show how it looks in code. So far I've only converted the `MainActivity`. 

My thinking now is that there is probably a better way to do the loop that the AsyncTask is doing. But perhaps that is out of scope of this issue? What do you think?

**Comment by andyb129** [comment]
Great, thanks for the conversion.  I've merged it in and we can do a few tweaks as we learn more about this Kotlin magic! 👍
